### ISSUE TITLE
pysap-etomo integration checklist

### ISSUE THREAD

**Issue by sfarrens** [CEA-COSMIC/pysap-etomo#4]
- [ ] Provides tools for applications not already covered by an existing PySAP plug-in (_e.g._ a new imaging domain)
- [ ] Makes appropriate use of PySAP and ModOpt tools (_i.e._ fits into PySAP framework and does not reinvent the wheel) 
- [ ] API consistent with existing PySAP plugins (_i.e._ naming conventions and architecture are consistent with other plug-ins)
- [ ] Any new dependencies justified
- [ ] Unit tests implemented in a consistent way
- [ ] Sufficient coverage of unit tests
- [ ] Docstrings implemented in a consistent way
- [ ] Docstrings clearly describe new functions/classes (_i.e._ is it clear for the user what all the functions and classes do)
- [ ] Example scripts and data available for testing

**Comment by sfarrens** [comment]
@AGrigis let me know if you have any comments/suggestions for this above checklist for integrating new plug-ins
